# coding=utf-8
MAX_STEER0: 25  #  
MAX_STEER0_1: 60
MAX_STEER1: 80  # k大于MAX_k时的上限（第3个区间）


MAX_k: 0.18     

MAX_lane: 130  # max lane error (-120,120)

P_para1:  1.5  # cmd = d_error * P_para1                   k is very min (k < MIN_k)

P_para20: 50 # cmd = （k * P_para20)^2 + P_para20_b      k is min      (MIN_k < k < max_steer_threshold)  
P_para20_b: 15

P_para21: 100  # cmd = P_para21 * P_para21 +P_para21_b   k is max      (k > max_steer_threshold)
P_para21_b: 10

P_all: 1   #

lane_warning: 75

2_value_thread: 100
die_area: 2    #
delta_value: 50 # used
bais: 40       #
t0: 100         #100  测试用
speed_value: 40

lane_memory: 1  #初始车道位置，1-left， 2-right  一般无须给定，除非在弯道等无法识别足够多点的地方


#path: 1
#path: 'data/ss-0.mp4'
#path: 'data/00010.mp4'
#path:  'data/allline.mp4'
path:  'data/lane_change1.mp4'
#path: 'data/line-1.mp4'
#path: 'data/shao-1.mp4'
#path: 'data/qian-2.mp4'
#path: 'data/11.mp4'
#path: 'data/slope-1.mp4'
#path: 'data/10.mp4'
#path: 'data/11.mp4'
MIN_k: 0.025



