# coding=utf-8
MAX_STEER0: 45  #  
MAX_STEER0_1: 60
MAX_STEER1: 85  # k大于MAX_k时的上限（第3个区间）


MAX_k: 0.18     

MAX_lane: 130  # max lane error (-120,120)

P_para1:  1.8  # cmd = d_error * P_para1                 k is very min (k < MIN_k)

P_para20: 35 # cmd = （k * P_para20)^2 + P_para20_b      k is min      (MIN_k < k < max_steer_threshold)  
P_para20_b: 20 #15

P_para21: 120  # cmd = P_para21 * P_para21 +P_para21_b   k is max      (k > max_steer_threshold)
P_para21_b: 25

P_all: 1   #

lane_warning: 75

2_value_thread: 100
die_area: 2    #
delta_value: 60 # used
bais: 0       #
lane_memory: 1  #初始车道位置，1-left， 2-right  一般无须给定，除非在弯道等无法识别足够多点的地方
#------------------------------
#  检查wifi 检查运算延时 是否循虚线
t0: 70         #100  测试用
speed_value: 70
dotted_line: 0   # 1 循虚线  0 循车道中心
#path: 1
#------------------------------
path: "192.168.31.228"
#path: data/ssss1.mp4
#path: 'data/ss-0.mp4'
#path: 'data/00010.mp4'
#path:  'data/allline.mp4'
#path:  'data/lane_change1.mp4'
#path: 'data/line-1.mp4'
#path: 'data/shao-1.mp4'
#path: 'data/qian-2.mp4'
#path: 'data/11.mp4'
#path: 'data/slope-1.mp4'
#path: 'data/10.mp4'
#path: 'data/11.mp4'
MIN_k: 0.025



